name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Checkout rgbds
        uses: actions/checkout@master
        with:
          path: rgbds
          ref: v0.5.2
          repository: gbdev/rgbds

      - name: Install rgbds
        working-directory: rgbds
        run: |
          sudo make install
          
      - name: Remove rgbds
        run: |
          rm -rf rgbds
          
      - name: Checkout pokered
        uses: actions/checkout@master
        with:
          path: pokered
          ref: v0.5.2
          repository: pret/pokered

      - name: Build pokered
        working-directory: pokered
        run: |
          make -j$(nproc)
          
      - name: Download UPS Patcher
        run: |
          wget https://github.com/rameshvarun/ups/releases/download/v0.2.0/linux-amd64.zip
          unzip linux-amd64.zip
          chmod a+x ups/ups
          
      - name: Make
        run: |
          make -j$(nproc)
          
      - name: Create Patch
        run: |
          ./ups/ups diff --base pokered/pokered.gbc --modified pokered.gbc --output rpp-ger.ups
          
      - name: Store Artifact
        uses: actions/upload-artifact@v3
        with:
          name: UPS Patch rpp-ger
          path: rpp-ger.ups
